config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :registres
  resources :users

  get '', to: 'static_pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'


  get 'csv/:id', to: 'registres#to_csv', :as => 'csv', defaults: { format: 'csv'}



  post 'authenticate', to: 'authentication#authenticate'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/registre.rb
require 'csv'
class Registre < ApplicationRecord

  belongs_to :user

  def self.to_csv
    attributes = %w{id created_at tipus}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |registre|
        csv << attributes.map do |attr|
          if attr == 'created_at'
            registre.created_at.localtime.to_formatted_s(:short)
          else
            registre.send(attr)
          end
        end
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email, case_sensitive: false
  validates_format_of :email, with: /@/

  has_many :registres

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  helper_method :authenticate_admin

  def require_login
    if !logged_in?
      redirect_to "/login"
    end
  end

  def authenticate_admin
    unless @current_user.role == 1
      render json: {error: 'Not Authorized'}, status: :unauthorized
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  #skip_before_action :authenticate_request
  #lkd

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])

    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
end

app/controllers/registres_controller.rb
class RegistresController < ApplicationController

  before_action :require_login

  def index
    regisres = Registre.all
    render json: regisres
  end

  def create
    registre = Registre.new(registre_params)
    if registre.save
      redirect_to '/'
    else
      render json: {status: 'ERROR', message: registre.errors},status: :unprocessable_entity
    end
  end

  def to_csv
    user = User.find(params[:id])
    registres = user.registres

    respond_to do |format|
      format.html
      format.csv { send_data registres.to_csv, filename: "#{user.name}-#{Date.today}.csv" }
    end

    #redirect_to user_path(params[:id])
  end

  def destroy
  end

  def show
  end

  def update
  end

  private

  def registre_params
    params.permit(:tipus).merge(user_id: @current_user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to '/'
    else
      render 'new'
    end
  end

  def new
  end

  def show
  end

  def update
  end

  def logout
  end

  def destroy
    #log_out
    redirect_to "/login"
  end

  private

  def user_params
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  #skip_before_action :authenticate_request
  before_action :require_login

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_action :authenticate_admin, only: [:index, :update, :destroy]
  before_action :require_login, only: [:index, :update, :destroy, :show]


  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: {status: 'SUCCESS', message:'User Created'},status: :ok
    else
      render json: {status: 'ERROR', message:@user.errors},status: :unprocessable_entity
    end
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
  end

  def update

  end


  private

  def user_params
    params.permit(:email, :name, :password, :password_confirmation, :role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Sigma Industrial Precision"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/registres_helper.rb
module RegistresHelper

  def entrada_marcada
    current_day = Time.now.strftime("%F")
    !entrada = @current_user.registres.detect { |registre| registre.created_at.strftime("%F") == current_day and registre.tipus == 'entrada' }.nil?
  end

  def sortida_marcada
    current_day = Time.now.strftime("%F")
    sortida = @current_user.registres.detect { |registre| registre.created_at.strftime("%F") == current_day and registre.tipus == 'sortida' }
    !entrada_marcada || !sortida.nil?
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Sigma Industrial Precision", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            	<% if @current_user.role == 1 %>
              		<li><%= link_to "Usuaris", '/users' %></li>
              	<% end%>
              	<li><%= link_to @current_user.name, current_user %></li>
              	<li><%= link_to "Sign out", '/logout' %></li>
            <% else %>
              <li><%= link_to "Sign in", '/login' %></li>
            <% end %>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1 id="date"><%= Time.now.to_formatted_s(:long) %></h1>
<div class="buttons"> 
	<%= button_to "MARCAR ENTRADA", registres_path(tipus: 'entrada'), method: :post, class: "btn btn-success", :disabled => entrada_marcada %>
	<%= button_to "MARCAR SORTIDA", registres_path(tipus: 'sortida'), method: :post, class: "btn btn-warning", :disabled => sortida_marcada %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table" style="width: 100%">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Usuari</th>
      <th scope="col">Últim Registre</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each.with_index do |user, index|%>
		<tr>
	      <th scope="row"><%= index + 1 %></th>
	      <td><%= link_to user.name, user_path(user), method: :get %></td>
	     <td><%= user.registres.last.created_at.to_formatted_s(:short) + " - " + user.registres.last.tipus.upcase %></td>
	    </tr>
	<% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= @user.name %>
</h1>
<div id="user-header">
  <h3>Registres</h3>
  <% if @current_user.role == 1 %>
    <div>
      <%= button_to "Exportar a fitxer .csv", csv_path(id: @user.id), method: :get %>
    </div>
  <% end%>
</div>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Hora</th>
      <th scope="col">Tipus</th>
    </tr>
  </thead>
  <tbody>
    <% @user.registres.each.with_index do |registre, index|%>
		<tr>
	      <th scope="row"><%= index + 1 %></th>
	      <td><%= registre.created_at.localtime.to_formatted_s(:short)  %></td>
	      <td><%= registre.tipus.upcase %></td>
	    </tr>
	<% end %>
  </tbody>
</table>